#!/bin/sh

while true; do
    rm images/*.tex
    for i in images/*.dia; do
        dia -t tex $i -e images/`basename $i .dia`.tex
    done
    pdflatex Аннотация.tex && pdflatex Диплом.tex
    
    rm *.log *.aux *.out images/*.tex
    
    inotifywait -e MOVE_SELF,MODIFY,CLOSE_WRITE *.tex images/*.dia
    sleep 1
done
