require 'rubygems'
require 'rake'
require 'spec/rake/spectask'

desc 'Run all specs'
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_opts = ['--format', 'specdoc', '--colour']
  t.spec_files = Dir['spec/**/*_spec.rb'].sort
end

desc 'RCov'
Spec::Rake::SpecTask.new('rcov') do |t|
  t.spec_opts = ['--format', 'specdoc', '--colour']
  t.spec_files = Dir['spec/**/*_spec.rb'].sort
  t.libs = ['lib']
  t.rcov = true
end
